# Generated by Django 5.2.3 on 2025-06-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
