# Generated by Django 5.2.3 on 2025-06-22 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offredestage',
            name='date_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite de candidature'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Premier participant'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_received', to=settings.AUTH_USER_MODEL, verbose_name='Second participant'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
