# Generated by Django 5.2.3 on 2025-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_departement_etudiant_last_annonce_vue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annonces_masquees',
            field=models.ManyToManyField(blank=True, to='stages.annonce'),
        ),
    ]
