# Generated by Django 5.2.3 on 2025-06-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_etudiant_annonces_masquees'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='validation_requested',
            field=models.BooleanField(default=True),
        ),
    ]
