# Generated by Django 5.2.3 on 2025-06-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0010_userprofile_validation_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='validation_requested',
        ),
    ]
