# Generated by Django 5.2.3 on 2025-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0011_remove_userprofile_validation_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='candidatures_lettres/'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio en ligne'),
        ),
    ]
