# Generated by Django 5.2.3 on 2025-07-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0012_candidature_lettre_motivation_etudiant_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='domaine_etude',
            field=models.CharField(choices=[('gc', 'Génie Civil'), ('geii', 'Génie Électrique et Informatique Industrielle'), ('gtr', 'Génie Télécom et Réseaux'), ('info', 'Informatique'), ('gindus', 'Génie Industriel'), ('chimie', 'Génie Chimique et Biologique'), ('gme', 'Génie Mécanique et Énergétique'), ('stats', 'Statistiques et Traitement de Données'), ('ges', 'Gestion'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau_etude',
            field=models.CharField(choices=[('licence1', 'Licence 1'), ('licence2', 'Licence 2'), ('licence3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2'), ('ingenieur1', 'Cycle Ingénieur 1'), ('ingenieur2', 'Cycle Ingénieur 2'), ('ingenieur3', 'Cycle Ingénieur 3')], max_length=20),
        ),
    ]
