# Generated by Django 5.2.3 on 2025-07-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0013_alter_etudiant_domaine_etude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='domaine_etude',
            field=models.CharField(choices=[('gc', 'Génie Civil'), ('geii', 'Génie Électrique et Informatique Industrielle'), ('gtr', 'Génie Télécom et Réseaux'), ('ginfo', 'Génie Informatique'), ('gindus', 'Génie Industriel'), ('chimie', 'Génie Chimique et Biologique'), ('gme', 'Génie Mécanique et Énergétique'), ('ges', 'Gestion'), ('autre', 'Autre')], max_length=20),
        ),
    ]
