# Generated by Django 5.2.3 on 2025-07-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0014_alter_etudiant_domaine_etude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoire',
            options={'verbose_name': 'Mémoire', 'verbose_name_plural': 'Mémoires'},
        ),
        migrations.AddField(
            model_name='memoire',
            name='contenu_textuel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
