# Generated by Django 5.2.3 on 2025-07-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0015_alter_memoire_options_memoire_contenu_textuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventiondestage',
            name='annee_universitaire',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='assurance',
            field=models.TextField(blank=True, default="Couverture par l'assurance de l'établissement", null=True),
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='avenant',
            field=models.FileField(blank=True, null=True, upload_to='avenants/'),
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='confidentialite_rapport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='fonction_tuteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='frais_remboursement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='materiel_fourni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='rapport_stage',
            field=models.FileField(blank=True, null=True, upload_to='rapports/'),
        ),
        migrations.AddField(
            model_name='conventiondestage',
            name='signature_enseignant',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
