# Generated by Django 5.2.3 on 2025-07-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0016_conventiondestage_annee_universitaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
