# Generated by Django 5.2.3 on 2025-07-06 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0017_etudiant_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(default='Dakar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(default='Sénégalaise', max_length=50),
        ),
    ]
