# Generated by Django 5.2.3 on 2025-07-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0018_etudiant_date_naissance_etudiant_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='pays',
            field=models.CharField(default='Sénégal', max_length=50),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='ville',
            field=models.CharField(default='Dakar', max_length=50),
        ),
    ]
