# Generated by Django 5.2.3 on 2025-07-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0019_etudiant_code_postal_etudiant_pays_etudiant_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='est_visible',
            field=models.BooleanField(default=True, help_text="Indique si l'annonce est visible par les étudiants"),
        ),
        migrations.AddField(
            model_name='annonce',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
