# Generated by Django 5.2.3 on 2025-07-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0020_annonce_est_visible_annonce_modifie_le'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('entretien_passe', 'Entretien passé'), ('en_attente', 'En attente de démarrage'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('commentaire_entreprise', models.TextField(blank=True, null=True)),
                ('commentaire_etudiant', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('convention', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.conventiondestage')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.entreprise')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stages.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.offredestage')),
            ],
        ),
    ]
